### ISSUE TITLE
ConsumerStream delay between requests

### ISSUE THREAD

**Issue by dennybritz** [confluentinc/kafka-rest-node#1]
It seems like the ConsumerStream is currently polling in a tight loop. This may result in the API server being overwhelmed with requests. If a topic receives messages only sporadically this can be inefficient. Depending on the topic the user may also be willing to accept a certain delay in exchange for better performance/batching.

Would it make sense to expose an option to introduce delay between successive topic GET requests?

**Comment by dennybritz** [comment]
Seems like an easy change, I'm happy to submit a PR for it, but wanted to discuss before doing it.

**Comment by ewencp** [comment]
Great point. As I went to find the right point in the kafka-rest docs to link to, I'm now noticing that this isn't clearly explained in the main API docs.

The server uses 2 variables to decide when to actually ship data back to the client:

1. Data size. This can be controlled per-request by the `max_bytes` query parameter and by the `consumer.request.max.bytes` configuration that applies to every request. The latter takes precedence over the former (so a user can't make the proxy consume many gigabytes of memory with a single request).
2. A request timeout, which is currently only controlled globally by the `consumer.request.timeout.ms` setting. You can see on the [config settings page](http://confluent.io/docs/current/kafka-rest/docs/config.html) that it is 1s by default.

The response will be sent whenever any of these conditions are satisfied.

So in this case, you won't have a *really* tight loop since each request will take 1s if there is no new data. That said, I agree that a fixed policy like this may not work for all applications. I think putting some control of the timeout in the users hands could be a good idea. Making the REST proxy handle this can be risky though (similar issue as with the memory example above, except the client could hold connections open for too long).

We could certainly also add control on the client side, which obviously has no impact on the server (except for lightening load). On the other hand, the obvious drawback is that your latency could go up, though some applications might be fine with that.

So thinking this through, I think my view is that it's possible even with the existing server-side timeouts, having client-side backoff could possibly be useful in some cases. So feel free to take a stab at it :)
