### ISSUE TITLE
Ability to pull messages by offset

### ISSUE THREAD

**Issue by atridgedcosta** [confluentinc/kafka-rest-node#12]
Is it possible to fetch 1 message at-a-time by partition using `kafka-rest-node`. It is already supported by the Kafka REST Proxy.

http://docs.confluent.io/2.0.0/kafka-rest/docs/api.html#get--topics-(string-topic_name)-partitions-(int-partition_id)-messages?offset=(int)[&count=(int)]

**Comment by ewencp** [comment]
@atridgedcosta That feature was added to the REST proxy after I initially developed this wrapper for the API, so it isn't currently supported. I think it'd be a pretty quick feature to add since it's just another endpoint under the `/topic/<topic>/partitions/<partition>` resource. If you want to try adding it, I'd be happy to offer some guidance on how to do so.

**Comment by atridgedcosta** [comment]
For sure! I had a quick look at the code. Where is the best place to add this? Partitions? Consumer?

**Comment by ewencp** [comment]
@atridgedcosta Generally I'd say you should organize them by the resource they are accessing, so in this case I'd say you want to add code to `lib/partition.js`. But since it's listed as a subresource (i.e. the endpoint is `/topic/<topic>/partitions/<partition>/messages`) you'll want to add a new resource class. A method of `Partition` should return the new resource type (much as a method of `Topic` returns a new `Partition`). Then, you'll want one method on the new resource called `messages` which will make the actual request. This should be mostly straightforward and similar to other examples (just a `GET` request via `this.client.get`), but will need to take parameters for `offset` and, optionally, `count`. You can pass these in via an (optional) `options` object and then customize the request with extra query parameters based on what's passed in.

Hopefully that provides the basic idea -- let me know if you have any other questions.

**Comment by data-catalysis** [comment]
@ewencp Thanks for your detail explanation. I am looking into your NodeJs code to find an implementation of this API, but it seems also have not provided yet: http://docs.confluent.io/2.0.0/kafka-rest/docs/api.html#post--consumers-(string-group_name)-instances-(string-instance)-offsets. Probably I need to implement it on my own for now, would you give me some hints to make it?

Also, to make use of this API: http://docs.confluent.io/2.0.0/kafka-rest/docs/api.html#get--topics-(string-topic_name)-partitions-(int-partition_id)-messages?offset=(int)[&count=(int)], we need the last committed **offset** as well as **count** which should correspond to the number of un-committed messages produced after the last committed. How could we keep track of such values within the settings of kafka consumers?

Many thanks.

**Comment by atridgedcosta** [comment]
@ewencp  Created a PR #13 for review

**Comment by jeffmontagna** [comment]
Can I use this implementation from a consumer?  If so, is there an example I can reference?
