### ISSUE TITLE
'socket.timeout.ms' is not working with that driver

### ISSUE THREAD

**Issue by lironess** [confluentinc/kafka-rest-node#15]
Hi.
I tried to consume from confluent 2.0 package and got error.
consume looked like:
```javascript
var kafkaRest = require('kafka-rest');

var kafka = new kafkaRest({ url: restProxyServerUrl });

kafka.consumer(myConsumerGroup).join(
  { 'format': `avro`, 'auto.offset.reset': `smallest`, 'socket.timeout.ms': `20000` }
  , function(error, consumer) {
    console.log(error);
  });
```

error is :
```
 [APIError: Unrecognized field: socket.timeout.ms]
auditclient_1 |   name: 'APIError',
auditclient_1 |   status: 422,
auditclient_1 |   message: 'Unrecognized field: socket.timeout.ms',
auditclient_1 |   data:
auditclient_1 |    { error_code: 422,
auditclient_1 |      message: 'Unrecognized field: socket.timeout.ms' } }
```

although that on kafka documentation there's that option:
```
socket.timeout.ms	| 30 * 1000 | The socket timeout for network requests. The actual timeout set will be max.fetch.wait + socket.timeout.ms.
```

**Comment by ewencp** [comment]
@lironess The REST proxy doesn't allow overriding all consumer configs on a per-consumer basis via the request. If you want to override this setting, you should do so via the REST proxy's config file, which will change it for all consumers.

There are a couple of reasons for this. First, allowing arbitrary overrides can be a bit risky in a shared service like the REST proxy. It's safer to selectively expose the critical configuration options for applications via the API, while allowing the operator of the service complete control. Second, since we knew the new consumer was being implemented and we'd ultimately want to switch to using it, we would prefer keeping a smaller set of options we know we'll be able to map to configs in either implementation so applications won't be affected when the switch is made.
